### PR TITLE
Update for 0.7

### PR DESCRIPTION
**Pull request by DavidHarrison**
The only changes needed for 0.7 were moving foreign functions into separate files, though I did also change the testing libraries over to `purescript-spec` as `purescript-mocha` and `purescript-chai` are not currently building with 0.7. Thanks for the helpful library!

### CODE REVIEW

**Comment by Fresheyeball** [comment]
Looks good, there is so much to update to 0.7 its really daunting, and I have zero time.

**Comment by DavidHarrison** [comment]
Thanks for adding it to Pursuit!

**Comment by Fresheyeball** [comment]
Yeah, README is not working for some reason. Bower is updated to.

**Comment by hdgarrood** [comment]
I think it will be because the v1.0.0 tag has not been pushed to github.

**Comment by paf31** [comment]
Ah makes sense, thanks.

**Comment by Fresheyeball** [comment]
Oh makes sense. I pushed but fogot to push tags. Perhaps the error message can be updated. My bad.

**Comment by hdgarrood** [comment]
Yeah, sounds like it would be worth exploring whether we can handle this better inside pursuit.

**Comment by Fresheyeball** [comment]
Ok, so tags pushed. Readme shows, but the badge is red for some reason.

**Comment by Fresheyeball** [comment]
Also just a workflow note on `psc-publish`
- try to publish
- get told you MUST be on a tag to publish
- tag the repo
- try to publish
- get told the bower file is wrong
- remove the tag
- update the bower file
- retag
- try to publish
- still something wrong with bower
- untag

ect...

point is, it would be nice if it checked the presence of a tag after or in tandem with other checks. I tend to use `bower version` which tags the repo and updates the bower file in one move. It would be nice to have `psc-publish` handle all of that and upload. That way `psc-publish v1.0.1` could check the `bower.json` then handle the hold enchilada... update the version in bower, tag the repo, push the tag to master, generate the `pursuit.json` and upload it.  As it stands I ended up using several tools to complete the process, and it feels like it could just be scripted.

**Comment by hdgarrood** [comment]
That's just the colour I chose :)

I agree, there's certainly lots of room for improvement in the current workflow. What you can do now (as long as you have 0.7.2) is do a `psc-publish --dry-run`, which won't require a tag to be checked out, and which won't produce anything, but otherwise is the same. Once that succeeds, you can tag and run `psc-publish` for real. We are also considering a pair of commands for pulp, `pulp version` and `pulp publish`, which build on top of this and make it a bit easier. See bodil/pulp#57

Come to think of it, I should update the guide on Pursuit with a note about the `--dry-run` flag.

**Pull request merged**
